{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Untitled1.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "id": "o-iJQDut4rSw",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "outputId": "a43151c8-3921-479b-9823-40d207632b5d"
      },
      "source": [
        " !pip install python-telegram-bot\n",
        "!pip install adafruit-io\n",
        "from telegram.ext import Updater,CommandHandler,MessageHandler,Filters\n",
        "from Adafruit_IO import Client,Data\n",
        "import os\n",
        "\n",
        "def turnoffthelight(update, context):\n",
        "  context.bot.send_message(chat_id=update.effective_chat.id, text=\"Bulb turned off\")\n",
        "  context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.123rf.com%2Fphoto_48123160_stock-vector-bright-glowing-incandescent-light-bulb-on-a-white-background.html&psig=AOvVaw1CM2JwdO30lTYALZS74qv5&ust=1600279369911000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJiFr63f6-sCFQAAAAAdAAAAABAD')\n",
        "  send_value(0)\n",
        "def turnonthelight(update, context):\n",
        "  context.bot.send_message(chat_id=update.effective_chat.id, text=\"Bulb turned on\")\n",
        "  context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.123rf.com%2Fphoto_48123160_stock-vector-bright-glowing-incandescent-light-bulb-on-a-white-background.html&psig=AOvVaw3yjACHWfoCfpBRg94DiNkB&ust=1600279074782000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPi77KDe6-sCFQAAAAAdAAAAABAD')\n",
        "  send_value(1)\n",
        "\n",
        "def send_value(value):\n",
        "  feed = aio.feeds('ashaj')\n",
        "  aio.send_data(feed.key,value)\n",
        "\n",
        "def input_message(update, context):\n",
        "  text=update.message.text\n",
        "  if text == 'turnonthelight':\n",
        "    send_value(1)\n",
        "    context.bot.send_message(chat_id=update.effective_chat.id,text=\"Bulb turned on\")\n",
        "    context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.123rf.com%2Fphoto_48123160_stock-vector-bright-glowing-incandescent-light-bulb-on-a-white-background.html&psig=AOvVaw1CM2JwdO30lTYALZS74qv5&ust=1600279369911000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJiFr63f6-sCFQAAAAAdAAAAABAD')\n",
        "  elif text == 'turnoffthelight':\n",
        "    send_value(0)\n",
        "    context.bot.send_message(chat_id=update.effective_chat.id,text=\"Bulb turned off\")\n",
        "    context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vector%2Fobject-bulb-off-vector-1858972&psig=AOvVaw15IuAn-EMouhd-qQ0y12_E&ust=1600279227128000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNj1mune6-sCFQAAAAAdAAAAABAD')\n",
        "\n",
        "def start(update,context):\n",
        "  start_message='''\n",
        "/turnoff the light or 'turn off':To turn off the bulb ,sends value=0 in feed\n",
        "/turnon the light or 'turn on'  :To turn on the bulb ,sends value=1 in feed\n",
        "'''\n",
        "  context.bot.send_message(chat_id=update.effective_chat.id, text=start_message)\n",
        "\n",
        "ADAFRUIT_IO_USERNAME =  os.getenv('ASHASHERIN')\n",
        "ADAFRUIT_IO_KEY = os.getenv('aio_zxbU99YhLwLjCrFQQQl2TFbUvYS0')\n",
        "TOKEN = os.getenv('1273321980:AAG-ssXNYmAqa3_kvtqUOzbIIGu5nOCXuNI')\n",
        "\n",
        "aio = Client('ASHASHERIN','aio_zxbU99YhLwLjCrFQQQl2TFbUvYS0')\n",
        "updater=Updater('1273321980:AAG-ssXNYmAqa3_kvtqUOzbIIGu5nOCXuNI',use_context=True)\n",
        "dispatcher = updater.dispatcher\n",
        "dispatcher.add_handler(CommandHandler('turnoffthelight',turnoffthelight))\n",
        "dispatcher.add_handler(CommandHandler('turnonthelight',turnonthelight))\n",
        "dispatcher.add_handler(CommandHandler('start',start))\n",
        "dispatcher.add_handler(MessageHandler(Filters.text & (~Filters.command),input_message))\n",
        "updater.start_polling()\n",
        "updater.idle()\n"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: python-telegram-bot in /usr/local/lib/python3.6/dist-packages (12.8)\n",
            "Requirement already satisfied: certifi in /usr/local/lib/python3.6/dist-packages (from python-telegram-bot) (2020.6.20)\n",
            "Requirement already satisfied: decorator>=4.4.0 in /usr/local/lib/python3.6/dist-packages (from python-telegram-bot) (4.4.2)\n",
            "Requirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.6/dist-packages (from python-telegram-bot) (5.1.1)\n",
            "Requirement already satisfied: cryptography in /usr/local/lib/python3.6/dist-packages (from python-telegram-bot) (3.1)\n",
            "Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from cryptography->python-telegram-bot) (1.15.0)\n",
            "Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.6/dist-packages (from cryptography->python-telegram-bot) (1.14.2)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi!=1.11.3,>=1.8->cryptography->python-telegram-bot) (2.20)\n",
            "Requirement already satisfied: adafruit-io in /usr/local/lib/python3.6/dist-packages (2.4.0)\n",
            "Requirement already satisfied: paho-mqtt in /usr/local/lib/python3.6/dist-packages (from adafruit-io) (1.5.0)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from adafruit-io) (2.23.0)\n",
            "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->adafruit-io) (1.24.3)\n",
            "Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->adafruit-io) (3.0.4)\n",
            "Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->adafruit-io) (2.10)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->adafruit-io) (2020.6.20)\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py\", line 340, in process_update\n",
            "    handler.handle_update(update, self, check, context)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/handler.py\", line 119, in handle_update\n",
            "    return self.callback(update, context)\n",
            "  File \"<ipython-input-1-d8f518cf4557>\", line 13, in turnonthelight\n",
            "    context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.123rf.com%2Fphoto_48123160_stock-vector-bright-glowing-incandescent-light-bulb-on-a-white-background.html&psig=AOvVaw3yjACHWfoCfpBRg94DiNkB&ust=1600279074782000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPi77KDe6-sCFQAAAAAdAAAAABAD')\n",
            "  File \"<decorator-gen-128>\", line 2, in send_photo\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 497, in send_photo\n",
            "    **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 175, in _message\n",
            "    result = self._request.post(url, data, timeout=timeout)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 244, in _request_wrapper\n",
            "    raise BadRequest(message)\n",
            "telegram.error.BadRequest: Failed to get http url content\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
          ],
          "name": "stderr"
        }
      ]
    }
  ]
}